#!/bin/sh

# Script: Coin_Flip (use 'coinflip' in CLI to run)
# Description: Simulates a coin flip with a genuine random algorithim
# Dependencies: None
# License: GPLv3
# Contributors: Shaun (ayylmaonde)

## Uses /dev/urandom to generate random variable, far superior to $RANDOM
flip=$(( $(head -c 1 /dev/urandom | od -An -t d) % 2 ))

if [ $flip -eq 1 ]; then
    echo "heads"
else
    echo "tails"
fi
